### ISSUE TITLE
how to get jasmine to report skips or fails?

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#27]
@ianwdunlop, I'm trying to run jasmine against the 2.1 API endpoint and expecting fails, so that I can fix those and to work on issue #25. But while I get an result over view for 1.5:

    jasmine-node --config app_id 91f5d4d0 --config app_key 1af5008d5f --config app_url https://beta.openphacts.org/1.5 test/spec/integration/ 
    .........................................................................................................................................
    
    Finished in 207.473 seconds
    137 tests, 1034 assertions, 0 failures, 0 skipped

When there is a fail with 2.1, it just seems to totally crash the jasmine job, without any info what goes wrong:

    jasmine-node --config app_id 91f5d4d0 --config app_key 1af5086da757e57c553bfa1351708d5f --config app_url https://beta.openphacts.org/2.1 test/spec/integration/TreeIntegrationSpec.js 
    ......................

That makes it really hard to debug it... before I delve into reporters, etc, what is the current behavior? Can I already find in some file which test fails? I already tried "--output" but don't think I was using that right.

**Comment by ianwdunlop** [comment]
If you run jasmine with "--captureExceptions" then it will report where the failures occurred after it has run the tests. I just tried with 2.1 and got a fail in StructureSearch. Everything else "seemed" to work. Which is of course a worry in itself!

**Comment by egonw** [comment]
I'll look into it!

**Comment by egonw** [comment]
(BTW, I'll set up a "2.1" branch, and send a PR when I'm comfortable with it...)

**Comment by egonw** [comment]
Confirmed it works! I'll make a patch for README.
