### ISSUE TITLE
delete merge branches?

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#28]
@ianwdunlop, maybe you can also have a look at all the development branches, and maybe delete all those which are merged into master already?

**Comment by ianwdunlop** [comment]
I think we can safely remove all except 
  origin/HEAD -> origin/master
  origin/develop
  origin/gh-pages
I'll do them when I get the chance

**Comment by ianwdunlop** [comment]
Pruned most of them (gosh github makes this too easy). Kept the ones mentioned above plus a couple of IRS2 ones in case it ever gets resurrected.

**Comment by egonw** [comment]
Thanks!
