### ISSUE TITLE
Does PathwaySearch.information() actually need the lens parameters?

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#8]
I know the lens parameter is available in the API too, but it is more frequently there in API methods where it is not used; I am not 100% sure, but do not see how the lens is used here either, as the resulting information contains a list of genes/protein/metabolites with one identifier, and no matter what lens is defined, those things are still part of that pathway. Or...? (It seems to me that the lens parameter is present in all API methods, even if not used/-full... do you know if that is intentional?)

**Comment by ianwdunlop** [comment]
Various points and questions raised and answered in the chat. No additional work required on OPS.js.
